#!/bin/bash
set -euo pipefail

# Generate a concrete README.md from project state
# Usage: generate-readme.sh [--project-dir <path>]
# Reads from .archetype-manifest.json, repos/, MAINTAINERS.json, the knowledge repo


# CR-safe jq (Windows jq emits CRLF; the CR survives $( ) and corrupts values).
_CRSAFE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
while [[ "$_CRSAFE" != "/" && ! -f "$_CRSAFE/scripts/lib/cr-safe-jq.sh" ]]; do
  _CRSAFE="$(dirname "$_CRSAFE")"
done
[[ -f "$_CRSAFE/scripts/lib/cr-safe-jq.sh" ]] && source "$_CRSAFE/scripts/lib/cr-safe-jq.sh"

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || echo "$(cd "$(dirname "$0")/../.." && pwd)")"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-dir) ROOT_DIR="$2"; shift 2 ;;
        *) shift ;;
    esac
done

cd "$ROOT_DIR"

# --- Read manifest ---
PROJECT_NAME=""
DESCRIPTION=""
LOG_REPO_NAME=""
if [[ -f .archetype-manifest.json ]] && command -v jq &>/dev/null; then
    PROJECT_NAME="$(jq -r '.template_values.PROJECT_NAME // empty' .archetype-manifest.json 2>/dev/null || true)"
    DESCRIPTION="$(jq -r '.template_values.description // empty' .archetype-manifest.json 2>/dev/null || true)"
    LOG_REPO_NAME="$(jq -r '.log_repo_name // empty' .archetype-manifest.json 2>/dev/null || true)"
fi
PROJECT_NAME="${PROJECT_NAME:-$(basename "$ROOT_DIR")}"
DESCRIPTION="${DESCRIPTION:-Multi-repo governance workspace.}"
LOG_REPO_NAME="${LOG_REPO_NAME:-${PROJECT_NAME}-knowledge}"

# --- Discover registered repos ---
REPO_TABLE=""
if [[ -d repos ]]; then
    for link in repos/*/; do
        [[ -L "${link%/}" || -d "$link" ]] || continue
        name="$(basename "${link%/}")"
        [[ "$name" == ".gitkeep" ]] && continue
        target="$(readlink -f "${link%/}" 2>/dev/null || echo "${link%/}")"
        # Detect purpose from AGENT.md repo map if available
        purpose=""
        if [[ -f AGENT.md ]]; then
            purpose="$(grep -oP "\\| ${name} \\|[^|]*\\| \\K[^|]+" AGENT.md 2>/dev/null | head -1 | xargs || true)"
        fi
        REPO_TABLE+="| ${name} | \`${target}\` | ${purpose:-—} |"$'\n'
    done
fi

# --- Check wiki state (the compiled wiki lives in the log repo) ---
WIKI_STATUS="No wiki pages compiled yet."
if [[ -d "repos/${LOG_REPO_NAME}/wiki" ]]; then
    wiki_count="$(find "repos/${LOG_REPO_NAME}/wiki" -name '*.md' -not -name 'INDEX.md' -not -name 'STALENESS.md' -not -name 'README.md' -not -name 'schema.md' -not -name 'USAGE.md' 2>/dev/null | wc -l)"
    if [[ "$wiki_count" -gt 0 ]]; then
        WIKI_STATUS="${wiki_count} wiki page(s) compiled in \`repos/${LOG_REPO_NAME}/wiki/\`."
    fi
fi

# --- Check log repo state ---
LOG_REPO_STATUS=""
LOG_REPO_DIR=""
if [[ -d "repos/${LOG_REPO_NAME}" ]]; then
    LOG_REPO_DIR="$(cd "repos/${LOG_REPO_NAME}" && pwd -P)"
    # `|| true` inside the substitution: under pipefail, find exiting 1 on a
    # not-yet-created subdirectory fails the whole pipeline and set -e kills
    # the script with no output at all (the strict-mode empty-path trap).
    progress_count="$( { find "$LOG_REPO_DIR/logs/progress" -name '*.md' 2>/dev/null || true; } | wc -l)"
    handoff_count="$( { find "$LOG_REPO_DIR/notes" -path '*/handoffs/*.md' 2>/dev/null || true; } | wc -l)"
    LOG_REPO_STATUS="${progress_count} progress report(s), ${handoff_count} handoff(s)"
fi

# --- Read maintainers ---
MAINTAINER_LIST=""
if [[ -f MAINTAINERS.json ]] && command -v jq &>/dev/null; then
    while IFS= read -r email; do
        [[ -n "$email" ]] && MAINTAINER_LIST+="- ${email}"$'\n'
    done < <(jq -r '.global_maintainers[]? // empty' MAINTAINERS.json 2>/dev/null || true)
fi

# --- Count hooks and skills ---
HOOK_COUNT=0
if [[ -f .claude/settings.json ]] && command -v jq &>/dev/null; then
    HOOK_COUNT="$(jq '[.hooks[] | .[].hooks | length] | add // 0' .claude/settings.json 2>/dev/null || echo 0)"
fi
OPTIONAL_HOOK_COUNT="$(find scripts/hooks -maxdepth 1 -name '*.sh' 2>/dev/null | wc -l)"
SKILL_COUNT="$(find .claude/skills -maxdepth 2 -name 'SKILL.md' 2>/dev/null | wc -l)"

# --- Generate README ---
cat > README.md << READMEEOF
<!-- Generated by scripts/utils/generate-readme.sh — re-run to refresh -->

# ${PROJECT_NAME}

${DESCRIPTION}

This is the **root governance repository** — it coordinates child repos through
shared agent policy, hooks, knowledge management, and cross-repo workflows.
No application code lives here.

## First-Time Setup (after cloning)

> **A fresh clone has working hooks and skills already.** \`CLAUDE.md\` /
> \`CODEX.md\`, \`.claude/settings.json\`, \`.claude/skills/\` and
> \`.claude/commands/\` are **tracked in git**, so cloning delivers them and a
> later \`git pull\` delivers new skills. What a clone does *not* have is the
> child repos under \`repos/\`, which are gitignored. Starting an
> agent session first will *not* set this up for you.

\`\`\`bash
bash scripts/bootstrap.sh
\`\`\`

That regenerates the engine adapters, re-clones the child repos recorded in
\`repos/repos.json\`, rebuilds the agent registry, and verifies the result. It is
safe to re-run. Then **restart your agent session** so the hooks in
\`.claude/settings.json\` are loaded.

Check an existing setup at any time with \`bash scripts/session/health_check.sh\`.

## Getting Started

\`\`\`bash
# Start an agent session (hooks handle context loading)
claude  # or codex

# Register a new child repo (also records it in repos/repos.json)
scripts/repos/register-repo.sh <name> <path> --purpose "description"

# Sync all registered repos
scripts/repos/sync-repos.sh
\`\`\`

## Registered Repos

| Repo | Path | Purpose |
|------|------|---------|
${REPO_TABLE:-| *(none yet)* | — | — |}

## Structure

\`\`\`
├── AGENT.md               # Engine-neutral agent instructions (primary)
├── MAINTAINERS.json       # Who can modify protected files
├── agents/
│   ├── shared/            # Cross-cutting policy (constraints, standards, workflows)
│   ├── roles/             # Role overlays (6-section schema per role)
│   └── prompt-templates/  # Optional prompt snippets copied to local/ at init
├── .claude/               # TRACKED: settings, skills (${SKILL_COUNT}), commands
├── scripts/
│   ├── bootstrap.sh       # One-shot setup for a fresh clone (run this first)
│   ├── hooks/             # Security gates, audit logging (${OPTIONAL_HOOK_COUNT} hooks)
│   ├── validate/          # Governance validators
│   ├── session/           # Session lifecycle
│   ├── repos/             # Child repo management
│   └── utils/             # Logging, analysis, generation
├── logs/                  # Stub — actual data in the knowledge repo
├── notes/                 # Stub — actual data in the knowledge repo
├── repos/
│   ├── ${LOG_REPO_NAME}/  # Knowledge repo (logs, notes, handoffs, research, compiled wiki + taxonomy)
│   └── <child-repo>/      # Registered application repos (symlink or physical)
├── secrets/               # Protected paths (contents gitignored)
├── local/                 # Per-machine customization (gitignored)
└── tmp/                   # Shared scratch — working files go HERE, not outside the tree
\`\`\`

> **Note**: \`AGENT.md\`, \`CLAUDE.md\`, \`CODEX.md\` and \`.claude/\` are all
> tracked in git — there is no generated engine layer. The old arrangement
> (engine files generated at init, gitignored) meant a skill committed to git
> reached nobody who had already initialized; do not reintroduce it.

Scratch work goes in **\`tmp/\`** — tracked as an empty directory, contents
gitignored. It is deliberately inside the tree: a sibling directory next to the
root clone is invisible to every other session and to the wrap-up survey, which
only walks \`.\` and \`repos/*/\`. Being ignored also means \`git add -A\` cannot
sweep it into a session PR. Nothing in \`tmp/\` survives a clean checkout; use
\`local/notes/\` for personal material that should persist.

## Log Repo

Session logs, notes, handoffs, and the compiled wiki live in a dedicated
**knowledge repo** at \`repos/${LOG_REPO_NAME}/\` (the \`log_repo_name\` in
\`.archetype-manifest.json\`). This is a separate git
repository with no branch protections — all team members can push logs freely,
even when the root repo has required reviews or CI gates.

| Directory | Contents |
|-----------|----------|
| \`logs/audit/<user>/\` | Per-user audit trails |
| \`logs/progress/<user>/\` | Daily session progress reports |
| \`logs/agent_audit.log\` | Append-only audit trail (JSONL) |
| \`notes/<user>/handoffs/\` | Work tracking documents (active/completed) |
| \`notes/<user>/research/\` | Per-member research intake (promoted to master by maintainers) |
| \`notes/<user>/facts.md\` | Cross-session facts cache |
| \`wiki/<user>/\` | Per-member wiki compilations |

$(if [[ -n "$LOG_REPO_STATUS" ]]; then echo "Current state: ${LOG_REPO_STATUS}."; else echo "Log repo not yet populated."; fi)

## Hooks

Hooks enforce policy during agent sessions. ${HOOK_COUNT} hooks are wired by default:

| Hook | Trigger | Purpose |
|------|---------|---------|
| \`session-start.sh\` | SessionStart | Resolve user, branch, load context |
| \`session-end.sh\` | SessionEnd | Write progress, push to log repo |
| \`check_secrets_read.sh\` | PreToolUse (Read) | Block reads of protected paths |
| \`check_filesystem_path.sh\` | PreToolUse (Write) | Prevent writes outside project |
| \`post-tool-use-audit.sh\` | PostToolUse | Append-only audit trail |
| \`check_clone_destination.sh\` | PreToolUse (Bash) | Block clones/worktrees landing outside the project |

Additional hooks available in \`scripts/hooks/\`. Enable via \`.claude/settings.json\`
or the init wizard. All hook commands use the \`\${CLAUDE_PROJECT_DIR:-.}/\` prefix
for reliable path resolution. See \`scripts/hooks/README.md\`.

## Skills

${SKILL_COUNT} skills available at \`.claude/skills/{name}/SKILL.md\` — that file
is the skill, tracked in git. No wrapper layer, no generation step.

| Skill | Trigger |
|-------|---------|
| \`project-wiki\` | "lint KB", "compile wiki", "what do we know about X" |
| \`research-intake\` | "research intake", "ingest this" |
| \`safe-commit\` | "safe commit", "commit with checks" |
| \`simplify\` | "simplify", "review code", "clean up" |
| \`new-skill\` | "create a skill", "scaffold skill" |
| \`new-handoff\` | "new handoff", "track work item" |
| \`init-wizard\` | Automatic when \`.needs-init\` exists |
| \`wrap-up\` | "wrap up", mid-session save, checkpoint progress |

## Prompt Templates

\`init-project.sh\` copies reusable brevity prompt templates from
\`agents/prompt-templates/brevity/\` into \`local/prompt-templates/brevity/\`.
The tracked copies are project-agnostic source material; the local copies are
safe to tailor to a team's models, roles, and scoring rubrics without creating
repo churn.

## Knowledge Management

Everyone produces into the knowledge repo — notes, progress reports, research
intake — and the compile step distils those per-user streams into the shared
wiki **in the same repo**. Nothing is compiled into the root repo: the wiki is
data, and data lives where every team member can push.

\`\`\`
 repos/${LOG_REPO_NAME}/ (any team member)
┌─────────────────────────────┐
│ notes/<user>/handoffs/      │
│ notes/<user>/plans/         │──┐
│ notes/<user>/research/      │  │
│ logs/progress/<user>/       │  │
└─────────────────────────────┘  │
                                 v
              ┌───────────────────────┐
              │ /project-wiki compile │
              └──────────┬────────────┘
                         v
┌─────────────────────────────┐
│ wiki/                       │  compiled articles + INDEX.md + STALENESS.md
│ (same repo, shared by all)  │  categories from wiki/taxonomy.yaml (same repo)
└─────────────────────────────┘
\`\`\`

${WIKI_STATUS}

- **Write to**: \`<knowledge-repo>/notes/<username>/\`, \`<knowledge-repo>/logs/progress/<username>/\`
- **Research intake**: \`/research-intake\` → \`<knowledge-repo>/notes/<username>/research/\`
- **Compile**: \`/project-wiki compile\` → \`<knowledge-repo>/wiki/\` (never the root repo)

## Child Repo Management

The root repo governs child repos hierarchically. Shared policy, roles, and
knowledge flow downward. Each child repo stays self-contained — the root adds
cross-repo awareness, not coupling.

\`\`\`
        ┌─────────────────────────┐
        │     ${PROJECT_NAME}      │
        │  shared policy & roles   │
        │  repos/<knowledge-repo>/ │
        │  agents/registry.json    │
        └──┬────────┬────────┬────┘
           │        │        │
     ┌─────┴──┐ ┌───┴────┐ ┌─┴──────┐
     │  repo  │ │  repo  │ │  repo  │
     │AGENT.md│ │AGENT.md│ │AGENT.md│
     └────────┘ └────────┘ └────────┘
\`\`\`

\`\`\`bash
scripts/repos/register-repo.sh <name> <path>       # Register a child repo
scripts/repos/register-repo.sh <name> <path> \\
  --no-scaffold                                     # Register without agent scaffolding
scripts/repos/scan-agents.sh                        # Discover agents across repos
scripts/repos/sync-repos.sh                         # Pull all registered repos
\`\`\`

## Maintainers

${MAINTAINER_LIST:-*(not yet configured)*}

## Validation

\`\`\`bash
python3 scripts/validate/validate_agents_structure.py      # Role file schema
python3 scripts/validate/validate_document_drift.py        # Structural integrity
python3 scripts/validate/validate_claude_md_consistency.py  # Instruction file refs
python3 scripts/validate/validate_skills.py                # Skill standards
\`\`\`
READMEEOF

echo "README.md generated for ${PROJECT_NAME}."
