#!/bin/bash
set -euo pipefail

# Generate a concrete README.md from project state
# Usage: generate-readme.sh [--project-dir <path>]
# Reads from .archetype-manifest.json, repos/, MAINTAINERS.json, knowledge/wiki/

ROOT_DIR="$(git rev-parse --show-toplevel 2>/dev/null || echo "$(cd "$(dirname "$0")/../.." && pwd)")"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project-dir) ROOT_DIR="$2"; shift 2 ;;
        *) shift ;;
    esac
done

cd "$ROOT_DIR"

# --- Read manifest ---
PROJECT_NAME=""
DESCRIPTION=""
LOG_REPO_NAME=""
if [[ -f .archetype-manifest.json ]] && command -v jq &>/dev/null; then
    PROJECT_NAME="$(jq -r '.template_values.PROJECT_NAME // empty' .archetype-manifest.json 2>/dev/null || true)"
    DESCRIPTION="$(jq -r '.template_values.description // empty' .archetype-manifest.json 2>/dev/null || true)"
    LOG_REPO_NAME="$(jq -r '.log_repo_name // empty' .archetype-manifest.json 2>/dev/null || true)"
fi
PROJECT_NAME="${PROJECT_NAME:-$(basename "$ROOT_DIR")}"
DESCRIPTION="${DESCRIPTION:-Multi-repo governance workspace.}"
LOG_REPO_NAME="${LOG_REPO_NAME:-${PROJECT_NAME}-logs}"

# --- Discover registered repos ---
REPO_TABLE=""
if [[ -d repos ]]; then
    for link in repos/*/; do
        [[ -L "${link%/}" || -d "$link" ]] || continue
        name="$(basename "${link%/}")"
        [[ "$name" == ".gitkeep" ]] && continue
        target="$(readlink -f "${link%/}" 2>/dev/null || echo "${link%/}")"
        # Detect purpose from AGENT.md repo map if available
        purpose=""
        if [[ -f AGENT.md ]]; then
            purpose="$(grep -oP "\\| ${name} \\|[^|]*\\| \\K[^|]+" AGENT.md 2>/dev/null | head -1 | xargs || true)"
        fi
        REPO_TABLE+="| ${name} | \`${target}\` | ${purpose:-—} |"$'\n'
    done
fi

# --- Check wiki state ---
WIKI_STATUS="No wiki pages compiled yet."
if [[ -d knowledge/wiki ]]; then
    wiki_count="$(find knowledge/wiki -name '*.md' 2>/dev/null | wc -l)"
    if [[ "$wiki_count" -gt 0 ]]; then
        WIKI_STATUS="${wiki_count} wiki page(s) compiled in \`knowledge/wiki/\`."
    fi
fi

# --- Check log repo state ---
LOG_REPO_STATUS=""
LOG_REPO_DIR=""
if [[ -d "repos/${LOG_REPO_NAME}" ]]; then
    LOG_REPO_DIR="$(cd "repos/${LOG_REPO_NAME}" && pwd -P)"
    progress_count="$(find "$LOG_REPO_DIR/logs/progress" -name '*.md' 2>/dev/null | wc -l)"
    handoff_count="$(find "$LOG_REPO_DIR/notes" -path '*/handoffs/*.md' 2>/dev/null | wc -l)"
    LOG_REPO_STATUS="${progress_count} progress report(s), ${handoff_count} handoff(s)"
fi

# --- Read maintainers ---
MAINTAINER_LIST=""
if [[ -f MAINTAINERS.json ]] && command -v jq &>/dev/null; then
    while IFS= read -r email; do
        [[ -n "$email" ]] && MAINTAINER_LIST+="- ${email}"$'\n'
    done < <(jq -r '.global_maintainers[]? // empty' MAINTAINERS.json 2>/dev/null || true)
fi

# --- Count hooks and skills ---
HOOK_COUNT=0
if [[ -f .claude/settings.json ]] && command -v jq &>/dev/null; then
    HOOK_COUNT="$(jq '[.hooks[] | .[].hooks | length] | add // 0' .claude/settings.json 2>/dev/null || echo 0)"
fi
OPTIONAL_HOOK_COUNT="$(find scripts/hooks -maxdepth 1 -name '*.sh' 2>/dev/null | wc -l)"
SKILL_COUNT="$(find agents/skills -maxdepth 2 -name 'SKILL.md' 2>/dev/null | wc -l)"

# --- Generate README ---
cat > README.md << READMEEOF
<!-- Generated by scripts/utils/generate-readme.sh — re-run to refresh -->

# ${PROJECT_NAME}

${DESCRIPTION}

This is the **root governance repository** — it coordinates child repos through
shared agent policy, hooks, knowledge management, and cross-repo workflows.
No application code lives here.

## Getting Started

\`\`\`bash
# Start an agent session (hooks handle context loading)
claude  # or codex

# Register a new child repo
scripts/repos/register-repo.sh <name> <path> --purpose "description"

# Sync all registered repos
scripts/repos/sync-repos.sh
\`\`\`

## Registered Repos

| Repo | Path | Purpose |
|------|------|---------|
${REPO_TABLE:-| *(none yet)* | — | — |}

## Structure

\`\`\`
├── AGENT.md               # Engine-neutral agent instructions (primary)
├── MAINTAINERS.json       # Who can modify protected files
├── agents/
│   ├── shared/            # Cross-cutting policy (constraints, standards, workflows)
│   ├── roles/             # Role overlays (6-section schema per role)
│   └── skills/            # Engine-neutral skill definitions (${SKILL_COUNT} skills)
├── scripts/
│   ├── hooks/             # Security gates, audit logging (${OPTIONAL_HOOK_COUNT} hooks)
│   ├── validate/          # Governance validators
│   ├── session/           # Session lifecycle
│   ├── repos/             # Child repo management
│   └── utils/             # Logging, analysis, generation
├── knowledge/             # Master wiki + research intake (maintainer-curated)
├── logs/                  # Stub — actual data in log repo
├── notes/                 # Stub — actual data in log repo
├── repos/
│   ├── ${LOG_REPO_NAME}/  # Log repo (session logs, notes, handoffs)
│   └── <child-repos>/     # Registered application repos
├── secrets/               # Protected paths (contents gitignored)
└── local/                 # Per-machine customization (gitignored)
\`\`\`

> **Note**: \`CLAUDE.md\`, \`CODEX.md\`, and \`.claude/\` are generated by
> \`scripts/utils/generate-engine.sh\` (called during init) and are gitignored.
> Only \`AGENT.md\` is committed.

## Log Repo

Session logs, notes, handoffs, and per-member wiki compilations live in a
dedicated **log repo** at \`repos/${LOG_REPO_NAME}/\`. This is a separate git
repository with no branch protections — all team members can push logs freely,
even when the root repo has required reviews or CI gates.

| Directory | Contents |
|-----------|----------|
| \`logs/audit/<user>/\` | Per-user audit trails |
| \`logs/progress/<user>/\` | Daily session progress reports |
| \`logs/agent_audit.log\` | Append-only audit trail (JSONL) |
| \`notes/<user>/handoffs/\` | Work tracking documents (active/completed) |
| \`notes/<user>/facts.md\` | Cross-session facts cache |
| \`wiki/<user>/\` | Per-member wiki compilations |

$(if [[ -n "$LOG_REPO_STATUS" ]]; then echo "Current state: ${LOG_REPO_STATUS}."; else echo "Log repo not yet populated."; fi)

## Hooks

Hooks enforce policy during agent sessions. ${HOOK_COUNT} hooks are wired by default:

| Hook | Trigger | Purpose |
|------|---------|---------|
| \`session-start.sh\` | SessionStart | Resolve user, branch, load context |
| \`session-end.sh\` | SessionEnd | Write progress, push to log repo |
| \`check_secrets_read.sh\` | PreToolUse (Read) | Block reads of protected paths |
| \`check_filesystem_path.sh\` | PreToolUse (Write) | Prevent writes outside project |
| \`post-tool-use-audit.sh\` | PostToolUse | Append-only audit trail |

Additional hooks available in \`scripts/hooks/\`. Enable via \`.claude/settings.json\`
or the init wizard. All hook commands use the \`\${CLAUDE_PROJECT_DIR:-.}/\` prefix
for reliable path resolution. See \`scripts/hooks/README.md\`.

## Skills

${SKILL_COUNT} skills available. Canonical definitions in \`agents/skills/\`.

| Skill | Trigger |
|-------|---------|
| \`project-wiki\` | "lint KB", "compile wiki", "what do we know about X" |
| \`research-intake\` | "research intake", "ingest this" |
| \`safe-commit\` | "safe commit", "commit with checks" |
| \`simplify\` | "simplify", "review code", "clean up" |
| \`new-skill\` | "create a skill", "scaffold skill" |
| \`new-handoff\` | "new handoff", "track work item" |
| \`init-wizard\` | Automatic when \`.needs-init\` exists |
| \`wrap-up\` | "wrap up", mid-session save, checkpoint progress |

## Knowledge Management

Per-user streams in the log repo feed into a shared master wiki in the root repo
through a two-tier compilation pipeline.

\`\`\`
 Log Repo                              Root Repo
┌─────────────────────────────┐       ┌──────────────────────┐
│ notes/<user>/handoffs/      │       │                      │
│ notes/<user>/plans/         │──┐    │                      │
│ logs/progress/<user>/       │  │    │                      │
└─────────────────────────────┘  │    │                      │
                                 v    │                      │
              ┌──────────────────────┐│                      │
              │ /project-wiki compile││                      │
              │ --user <username>    ││                      │
              └──────────┬───────────┘│                      │
                         v            │                      │
┌─────────────────────────────┐       │                      │
│ wiki/<user>/                │──┐    │                      │
│ (per-member wiki)           │  │    │                      │
└─────────────────────────────┘  │    │                      │
                                 v    │                      │
              ┌──────────────────────┐│                      │
              │ /project-wiki compile││  knowledge/wiki/     │
              │ --master             │├─>(master wiki)       │
              │ (maintainer only,    ││  compiled, cross-    │
              │  auto when member    ││  user, cited,        │
              │  compiles own wiki)  ││  queryable           │
              └──────────────────────┘│                      │
                                      │  knowledge/research/ │
              ┌──────────────────────┐│  (external intake)   │
              │ /research-intake     │├─>deep-dives/         │
              │ URLs, papers,        ││                      │
              │ benchmarks           ││                      │
              └──────────────────────┘└──────────────────────┘
\`\`\`

${WIKI_STATUS}

- **Write to**: \`<log-repo>/notes/<username>/\`, \`<log-repo>/logs/progress/<username>/\`
- **Per-member wiki**: \`/project-wiki compile --user <name>\` → \`<log-repo>/wiki/<name>/\`
- **Master wiki**: \`/project-wiki compile --master\` → \`knowledge/wiki/\` (maintainer, auto-triggered)
- **Ingest external**: \`/research-intake\` → \`knowledge/research/\`

## Child Repo Management

The root repo governs child repos hierarchically. Shared policy, roles, and
knowledge flow downward. Each child repo stays self-contained — the root adds
cross-repo awareness, not coupling.

\`\`\`
        ┌─────────────────────────┐
        │     ${PROJECT_NAME}      │
        │  shared policy & roles   │
        │  knowledge/wiki/         │
        │  agents/registry.json    │
        └──┬────────┬────────┬────┘
           │        │        │
     ┌─────┴──┐ ┌───┴────┐ ┌─┴──────┐
     │  repo  │ │  repo  │ │  repo  │
     │AGENT.md│ │AGENT.md│ │AGENT.md│
     └────────┘ └────────┘ └────────┘
\`\`\`

\`\`\`bash
scripts/repos/register-repo.sh <name> <path>       # Register a child repo
scripts/repos/register-repo.sh <name> <path> \\
  --no-scaffold                                     # Register without agent scaffolding
scripts/repos/scan-agents.sh                        # Discover agents across repos
scripts/repos/sync-repos.sh                         # Pull all registered repos
\`\`\`

## Maintainers

${MAINTAINER_LIST:-*(not yet configured)*}

## Validation

\`\`\`bash
python3 scripts/validate/validate_agents_structure.py      # Role file schema
python3 scripts/validate/validate_document_drift.py        # Structural integrity
python3 scripts/validate/validate_claude_md_consistency.py  # Instruction file refs
python3 scripts/validate/validate_skills.py                # Skill standards
\`\`\`
READMEEOF

echo "README.md generated for ${PROJECT_NAME}."
