#!/usr/bin/env bash
# Spawn integrity test.
#
# Answers one question deterministically: **can this archetype create a
# correctly structured and wired fresh root project?**
#
# Everything else in this repo tests a part in isolation. Hook unit tests pass,
# CI passes, and a spawned project could still ship with a failing validator,
# audit entries written to the wrong repo, and security layers inert -- all of
# which was true on 2026-08-29 and none of which was visible from a diff.
#
# Usage:  bash scripts/validate/test_spawn.sh [--keep]
#         --keep   leave the spawned project on disk for inspection
#
# Exits 0 only if every assertion passes.

set -uo pipefail   # deliberately NOT -e: every check must run and report

ARCHETYPE_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
KEEP=0
[[ "${1:-}" == "--keep" ]] && KEEP=1

PASS=0; FAIL=0
ok()   { PASS=$((PASS + 1)); printf '  ok   %s\n' "$1"; }
bad()  { FAIL=$((FAIL + 1)); printf '  FAIL %s\n         %s\n' "$1" "${2:-}"; }

SANDBOX="$(mktemp -d)"
cleanup() { [[ $KEEP -eq 1 ]] || rm -rf "$SANDBOX"; }
trap cleanup EXIT

PROJ="spawntest"
DEST="$SANDBOX/$PROJ"

echo "=== spawn integrity test"
echo "  archetype: $ARCHETYPE_DIR"
echo "  sandbox:   $SANDBOX"
echo ""

# --- Spawn ---------------------------------------------------------------
# GH_CONFIG_DIR at an empty dir makes `gh auth status` fail, so init leaves
# GH_USER empty and never runs `gh repo create`. Without this the test would
# create a real private repo on every run.
mkdir -p "$SANDBOX/no-gh"
SPAWN_LOG="$SANDBOX/spawn.log"
( cd "$ARCHETYPE_DIR" && GH_CONFIG_DIR="$SANDBOX/no-gh" \
    timeout 300 bash init-project.sh "$PROJ" --copy-to "$DEST" \
        --description "spawn integrity test" ) >"$SPAWN_LOG" 2>&1
rc=$?
if [[ $rc -eq 0 ]]; then ok "init-project.sh exits 0"
else bad "init-project.sh exits 0" "exit=$rc; see $SPAWN_LOG"; echo ""; echo "FAILED early: $PASS passed, $FAIL failed"; exit 1; fi

if grep -q "gh repo create\|Creating GitHub repo" "$SPAWN_LOG"; then
    bad "no GitHub repo was created" "init tried to create a remote repo"
else ok "no GitHub repo was created"; fi

cd "$DEST" || { echo "spawn destination missing"; exit 1; }
KNOW="repos/${PROJ}-knowledge"

# --- Structure -----------------------------------------------------------
[[ -d "$KNOW" ]] && ok "knowledge repo at $KNOW" \
                 || bad "knowledge repo at $KNOW" "not found"
[[ -d "$KNOW/.git" ]] && ok "knowledge repo is a git repo" \
                      || bad "knowledge repo is a git repo" "no .git"
[[ -f .archetype-manifest.json ]] && ok "manifest written" \
                                  || bad "manifest written" "missing"
name="$(jq -r '.log_repo_name // empty' .archetype-manifest.json 2>/dev/null)"
[[ "$name" == "${PROJ}-knowledge" ]] && ok "manifest log_repo_name = ${PROJ}-knowledge" \
                                     || bad "manifest log_repo_name" "got '$name'"
[[ -d .claude && -f .claude/settings.json ]] && ok ".claude/ present and tracked-style" \
                                             || bad ".claude/ present" "missing"
[[ ! -d knowledge ]] && ok "archetype-internal knowledge/ NOT copied" \
                     || bad "archetype-internal knowledge/ NOT copied" "knowledge/ exists in the project"

# --- Audit routing -------------------------------------------------------
# The April 2026 split moved all log data into the knowledge repo. Entries in
# the ROOT repo mean something resolved the log repo wrongly, and they exist in
# the knowledge repo nowhere at all.
root_entries=0
[[ -f logs/agent_audit.log ]] && root_entries="$(wc -l < logs/agent_audit.log | tr -d ' ')"
[[ "$root_entries" -eq 0 ]] && ok "no audit entries in the ROOT repo" \
                            || bad "no audit entries in the ROOT repo" \
                                   "$root_entries entries in logs/agent_audit.log"

know_entries=0
[[ -f "$KNOW/logs/agent_audit.log" ]] && know_entries="$(wc -l < "$KNOW/logs/agent_audit.log" | tr -d ' ')"
[[ "$know_entries" -gt 0 ]] && ok "audit entries land in the knowledge repo ($know_entries)" \
                            || bad "audit entries land in the knowledge repo" "found none"

# A malformed field means provenance resolution is broken even though the
# entry was written to the right place.
if [[ -f "$KNOW/logs/agent_audit.log" ]]; then
    if bad_branch="$(jq -r 'select((.branch // "") | test("\n")) | .branch' \
                      "$KNOW/logs/agent_audit.log" 2>/dev/null | head -1)" \
       && [[ -n "$bad_branch" ]]; then
        bad "audit branch field is well-formed" "multi-line branch value recorded"
    else ok "audit branch field is well-formed"; fi
fi

# --- Security baseline ---------------------------------------------------
[[ -f scripts/hooks/lib/tools.lock ]] && ok "tools.lock generated by init" \
                                      || bad "tools.lock generated by init" "absent — tool pinning inactive"
[[ -f HOOKS.lock ]] && ok "HOOKS.lock generated by init" \
                    || bad "HOOKS.lock generated by init" "absent — drift detection inactive"

# --- Validators ----------------------------------------------------------
for v in scripts/validate/validate_*.sh; do
    [[ -f "$v" ]] || continue
    if bash "$v" >/dev/null 2>&1; then ok "$(basename "$v")"
    else bad "$(basename "$v")" "exit non-zero in a fresh project"; fi
done
for v in scripts/validate/validate_*.py; do
    [[ -f "$v" ]] || continue
    if python3 "$v" >/dev/null 2>&1; then ok "$(basename "$v")"
    else bad "$(basename "$v")" "exit non-zero in a fresh project"; fi
done

# --- Hooks are actually wired -------------------------------------------
wired="$(grep -o 'hooks/[a-z_-]*\.sh' .claude/settings.json 2>/dev/null | sort -u | wc -l | tr -d ' ')"
[[ "$wired" -ge 5 ]] && ok "$wired hooks wired in .claude/settings.json" \
                     || bad "hooks wired in .claude/settings.json" "only $wired"

for t in scripts/hooks/tests/*.sh; do
    [[ -f "$t" ]] || continue
    if bash "$t" >/dev/null 2>&1; then ok "$(basename "$t")"
    else bad "$(basename "$t")" "hook test fails in a fresh project"; fi
done

# --- Day-one paths -------------------------------------------------------
# These are the paths least likely to be exercised before release: empty
# directories, zero counters, no notes yet.
if bash scripts/build-indexes.sh >/dev/null 2>&1; then ok "build-indexes.sh on an empty project"
else bad "build-indexes.sh on an empty project" "non-zero exit"; fi

hout="$(bash scripts/utils/generate-handoff-index.sh 2>&1 | tail -1)"
if grep -q "0 entries, 0 users" <<<"$hout"; then
    ok "handoff index reports 0 users on day one"
else
    bad "handoff index reports 0 users on day one" "got: $hout"
fi

if [[ -f "$KNOW/notes/handoffs/INDEX.md" ]]; then
    n="$(grep -c '^## *$' "$KNOW/notes/handoffs/INDEX.md" || true)"
    [[ "$n" -eq 0 ]] && ok "handoff index has no headerless sections" \
                     || bad "handoff index has no headerless sections" "$n found"
fi

# --- session-start in the throwaway --------------------------------------
if CLAUDE_PROJECT_DIR="$DEST" timeout 60 bash scripts/hooks/session-start.sh --argv >/dev/null 2>&1; then
    ok "session-start.sh --argv"
else bad "session-start.sh --argv" "non-zero exit"; fi

echo ""
echo "=== $PASS passed, $FAIL failed"
[[ $KEEP -eq 1 ]] && echo "    sandbox kept at $SANDBOX"
[[ $FAIL -eq 0 ]]
